# Osnovna ZMK podesavanja
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# BLE
CONFIG_BT_DEVICE_NAME="Tastatura za posebne potrebe"

# Opcionalno: ukljuci USB HID ako hoces i zicanu vezu
# CONFIG_ZMK_USB=y
